//! Raster overlay upsampler.
//!
//! Given a parent [`GltfModel`] and a target quadtree child quadrant, this
//! produces a new glTF that contains only the geometry belonging to that
//! child. Triangles that straddle the boundary are clipped and new vertices
//! are interpolated.
//!
//! # Usage
//!
//! ```ignore
//! let child = upsample_gltf_for_overlay(
//!     &parent_model,
//!     UpsampleChildId { x: 1, y: 0, level: 3 },
//!     true,           // v=0 is north (inverted V, glTF convention)
//!     "TEXCOORD_",    // attribute base name used for clipping
//!     0,              // -> clips using TEXCOORD_0
//!     &terra::Ellipsoid::wgs84(),
//! );
//! ```
//!
//! The selected UV attribute is used **only** as a guide for clipping and is
//! **excluded** from the output (it will be regenerated by the overlay engine
//! for the child tile). All other float attributes - including regular
//! `TEXCOORD_0` if that is not the clipping attribute - are interpolated and
//! kept in the output.

use glam::DVec3;
use moderu::{
    Accessor, AccessorComponentType, AccessorType, Buffer, BufferView, GltfModel, MeshPrimitive,
};

use moderu::SkirtMeshMetadata;

/// Identifies which child quadrant to generate.
///
/// The quadrant is determined by the tile ID at the next zoom level:
/// - `x % 2 == 0` -> west half; `x % 2 == 1` -> east half.
/// - `y % 2 == 0` -> south half; `y % 2 == 1` -> north half
///   (when `has_inverted_v = false`).
#[derive(Debug, Clone, Copy)]
pub struct UpsampleChildId {
    pub x: u32,
    pub y: u32,
    pub level: u32,
}

impl UpsampleChildId {
    #[inline]
    fn is_west(&self) -> bool {
        self.x % 2 == 0
    }
    #[inline]
    fn is_south(&self) -> bool {
        self.y % 2 == 0
    }
}

/// Produce a new [`GltfModel`] containing the geometry belonging to
/// the given child quadrant of `parent`.
///
/// - `has_inverted_v` - `true` when the UV attribute has `v = 0` at the
///   **north** edge and `v = 1` at the south (standard glTF / sovra
///   TEXCOORD_0 convention).
/// - `texcoord_attr_base` + `texcoord_index` - name of the UV attribute to
///   use as the clipping guide (e.g. `"TEXCOORD_"` and `0` -> `"TEXCOORD_0"`).
///   This attribute is **excluded** from the output.
/// - `ellipsoid` - used to push skirt vertices along the surface normal.
///
/// Returns `None` if the parent model has no mesh primitives, or if all
/// primitives fall entirely outside the child quadrant.
pub fn upsample_gltf_for_overlay(
    parent: &GltfModel,
    child_id: UpsampleChildId,
    has_inverted_v: bool,
    texcoord_attr_base: &str,
    texcoord_index: u32,
    ellipsoid: &terra::Ellipsoid,
) -> Option<GltfModel> {
    // Build the output model by shallow-cloning everything except buffers,
    // buffer_views, and accessors (which we rebuild from scratch).
    let mut result = selective_clone(parent);

    let uv_attr_name = format!("{texcoord_attr_base}{texcoord_index}");
    let mut any_kept = false;

    // Process every primitive in each mesh.  We iterate by index so we can
    // modify result.meshes[i].primitives[j] in place.
    for mesh_i in 0..result.meshes.len() {
        let mut prim_i = 0;
        while prim_i < result.meshes[mesh_i].primitives.len() {
            let kept = upsample_primitive(
                parent,
                &mut result,
                mesh_i,
                prim_i,
                child_id,
                has_inverted_v,
                texcoord_attr_base,
                &uv_attr_name,
                ellipsoid,
            );
            if kept {
                any_kept = true;
                prim_i += 1;
            } else {
                result.meshes[mesh_i].primitives.remove(prim_i);
            }
        }
    }

    if any_kept { Some(result) } else { None }
}

/// Clone selected fields of `parent` into a new [`GltfModel`] for upsampling.
///
/// Copies geometry-relevant data (`images`, `materials`, `meshes`, `nodes`,
/// `samplers`, `scenes`, `textures`) while leaving `buffers`, `buffer_views`,
/// and `accessors` empty — those are rebuilt from scratch during upsampling.
/// `animations`, `cameras`, and `skins` are also omitted since they play no
/// role in geometry clipping.
///
/// **Note:** this performs a full deep clone of the included Vecs.  If any
/// of those Vecs are large (many materials, textures, etc.) the cost is
/// proportional to their total size.  In typical 3D-Tiles usage they are
/// small (< 10 elements each).
fn selective_clone(parent: &GltfModel) -> GltfModel {
    GltfModel {
        // Omit animations, cameras, skins - not used in upsampling
        animations: Vec::new(),
        asset: parent.asset.clone(),
        cameras: Vec::new(),
        extensions: parent.extensions.clone(),
        extensions_required: parent.extensions_required.clone(),
        extensions_used: parent.extensions_used.clone(),
        extras: parent.extras.clone(),
        images: parent.images.clone(),
        materials: parent.materials.clone(),
        meshes: parent.meshes.clone(),
        nodes: parent.nodes.clone(),
        samplers: parent.samplers.clone(),
        scene: parent.scene,
        scenes: parent.scenes.clone(),
        skins: Vec::new(),
        textures: parent.textures.clone(),
        ..Default::default()
    }
}

/// A vertex in a triangle-clip result.
///
/// Negative indices (`< 0`) are bitwise-NOT encoded
/// and refer back into the *complements* array of the previous clip pass:
/// index `-1` (= `!0`) -> `complements[0]`, `-2` (= `!1`) -> `complements[1]`,
/// and so on.
#[derive(Clone, Copy, Debug)]
enum CV {
    /// Non-negative: direct parent vertex index.
    /// Negative (= `!ci`): reference into `complements[ci]`.
    Index(i32),
    /// Linear interpolation between two vertices.  `first` and `second` use
    /// the same encoding as `Index`.
    Interp { first: i32, second: i32, t: f64 },
}

/// Clip a triangle against an axis-aligned threshold and push the surviving
/// polygon vertices (0, 3, or 4 points) onto `result`.
///
/// Direct port of `CesiumGeometry::clipTriangleAtAxisAlignedThreshold`.
fn clip_triangle(
    threshold: f64,
    keep_above: bool,
    i0: i32,
    i1: i32,
    i2: i32,
    u0: f64,
    u1: f64,
    u2: f64,
    result: &mut Vec<CV>,
) {
    let behind = |u: f64| -> bool {
        if keep_above {
            u < threshold
        } else {
            u > threshold
        }
    };
    let b0 = behind(u0);
    let b1 = behind(u1);
    let b2 = behind(u2);
    let n_behind = b0 as i32 + b1 as i32 + b2 as i32;

    match n_behind {
        0 => {
            // All in front - keep as-is.
            result.push(CV::Index(i0));
            result.push(CV::Index(i1));
            result.push(CV::Index(i2));
        }
        3 => {
            // All behind - discard.
        }
        1 => {
            if b0 {
                let t01 = (threshold - u0) / (u1 - u0);
                let t02 = (threshold - u0) / (u2 - u0);
                result.push(CV::Index(i1));
                result.push(CV::Index(i2));
                if t02 != 1.0 {
                    result.push(CV::Interp {
                        first: i0,
                        second: i2,
                        t: t02,
                    });
                }
                if t01 != 1.0 {
                    result.push(CV::Interp {
                        first: i0,
                        second: i1,
                        t: t01,
                    });
                }
            } else if b1 {
                let t12 = (threshold - u1) / (u2 - u1);
                let t10 = (threshold - u1) / (u0 - u1);
                result.push(CV::Index(i2));
                result.push(CV::Index(i0));
                if t10 != 1.0 {
                    result.push(CV::Interp {
                        first: i1,
                        second: i0,
                        t: t10,
                    });
                }
                if t12 != 1.0 {
                    result.push(CV::Interp {
                        first: i1,
                        second: i2,
                        t: t12,
                    });
                }
            } else {
                // b2
                let t20 = (threshold - u2) / (u0 - u2);
                let t21 = (threshold - u2) / (u1 - u2);
                result.push(CV::Index(i0));
                result.push(CV::Index(i1));
                if t21 != 1.0 {
                    result.push(CV::Interp {
                        first: i2,
                        second: i1,
                        t: t21,
                    });
                }
                if t20 != 1.0 {
                    result.push(CV::Interp {
                        first: i2,
                        second: i0,
                        t: t20,
                    });
                }
            }
        }
        2 => {
            if !b0 && u0 != threshold {
                let t10 = (threshold - u1) / (u0 - u1);
                let t20 = (threshold - u2) / (u0 - u2);
                result.push(CV::Index(i0));
                result.push(CV::Interp {
                    first: i1,
                    second: i0,
                    t: t10,
                });
                result.push(CV::Interp {
                    first: i2,
                    second: i0,
                    t: t20,
                });
            } else if !b1 && u1 != threshold {
                let t21 = (threshold - u2) / (u1 - u2);
                let t01 = (threshold - u0) / (u1 - u0);
                result.push(CV::Index(i1));
                result.push(CV::Interp {
                    first: i2,
                    second: i1,
                    t: t21,
                });
                result.push(CV::Interp {
                    first: i0,
                    second: i1,
                    t: t01,
                });
            } else if !b2 && u2 != threshold {
                let t02 = (threshold - u0) / (u2 - u0);
                let t12 = (threshold - u1) / (u2 - u1);
                result.push(CV::Index(i2));
                result.push(CV::Interp {
                    first: i0,
                    second: i2,
                    t: t02,
                });
                result.push(CV::Interp {
                    first: i1,
                    second: i2,
                    t: t12,
                });
            }
        }
        _ => unreachable!(),
    }
}

/// A reference into the parent model's raw buffer for a single float attribute.
struct FloatAttr<'a> {
    /// Backing bytes (the whole buffer, not just the buffer view).
    data: &'a [u8],
    /// `buffer_view.byte_offset + accessor.byte_offset`.
    byte_offset: usize,
    /// Bytes between consecutive vertices.
    stride: usize,
    /// Number of `f32` components per vertex.
    num_floats: usize,
    /// Index of the corresponding accessor in the **output** model.
    out_acc_idx: usize,
}

/// Recursively evaluate a `CV` entry into a flat `Vec<f32>`.
/// Handles negative-encoded references into `complements`.
fn eval_cv(attrs: &[FloatAttr<'_>], complements: &[CV], v: CV) -> Vec<f32> {
    match v {
        CV::Index(i) if i < 0 => eval_cv(attrs, complements, complements[(!i) as usize]),
        CV::Index(i) => {
            let idx = i as usize;
            attrs
                .iter()
                .flat_map(|a| {
                    let base = a.byte_offset + idx * a.stride;
                    (0..a.num_floats).map(move |c| {
                        let s = base + c * 4;
                        f32::from_le_bytes(a.data[s..s + 4].try_into().unwrap())
                    })
                })
                .collect()
        }
        CV::Interp { first, second, t } => {
            let v0 = eval_cv(attrs, complements, CV::Index(first));
            let v1 = eval_cv(attrs, complements, CV::Index(second));
            v0.iter()
                .zip(&v1)
                .map(|(&a, &b)| (a as f64 + (b as f64 - a as f64) * t) as f32)
                .collect()
        }
    }
}

/// Get-or-create a vertex in the interleaved output buffer.
///
/// Non-negative `CV::Index` vertices are cached in `vertex_map` to avoid
/// duplication; interpolated vertices are always new.
fn get_or_create(
    new_floats: &mut Vec<f32>,
    attrs: &[FloatAttr<'_>],
    complements: &[CV],
    v: CV,
    vertex_size: usize,
    vertex_map: &mut [u32],
) -> u32 {
    // Resolve through complements first (keep the resolved form for caching).
    let resolved = resolve_through_complements(complements, v);

    if let CV::Index(i) = resolved {
        if i >= 0 {
            let idx = i as usize;
            if vertex_map[idx] != u32::MAX {
                return vertex_map[idx];
            }
        }
    }

    let floats = eval_cv(attrs, complements, resolved);
    let new_idx = (new_floats.len() / vertex_size) as u32;
    new_floats.extend_from_slice(&floats);

    if let CV::Index(i) = resolved {
        if i >= 0 {
            vertex_map[i as usize] = new_idx;
        }
    }
    new_idx
}

fn resolve_through_complements(complements: &[CV], v: CV) -> CV {
    match v {
        CV::Index(i) if i < 0 => {
            resolve_through_complements(complements, complements[(!i) as usize])
        }
        other => other,
    }
}

#[derive(Default)]
struct EdgeIndices {
    west: Vec<EdgeVertex>,
    south: Vec<EdgeVertex>,
    east: Vec<EdgeVertex>,
    north: Vec<EdgeVertex>,
}

struct EdgeVertex {
    new_index: u32,
    uv: [f32; 2],
}

const EPSILON4: f32 = 1e-4;

/// Record which new vertices ended up on tile boundary edges.
fn record_edge_vertices(
    edges: &mut EdgeIndices,
    threshold_u: f32,
    threshold_v: f32,
    keep_above_u: bool,
    keep_above_v: bool,
    invert_v: bool,
    clip_vertex_to_index: &[u32],
    uv_attrs: &[FloatAttr<'_>],
    complements: &[CV],
    clip_result: &[CV],
) {
    for (&new_idx, cv) in clip_vertex_to_index.iter().zip(clip_result.iter()) {
        let uv_floats = eval_cv(uv_attrs, complements, *cv);
        let uv = [uv_floats[0], uv_floats[1]];

        let u = uv[0];
        let v = uv[1];
        let south_v = if invert_v { 1.0 } else { 0.0 };
        let north_v = if invert_v { 0.0 } else { 1.0 };

        if (u - 0.0).abs() < EPSILON4 {
            edges.west.push(EdgeVertex {
                new_index: new_idx,
                uv,
            });
        }
        if (u - 1.0).abs() < EPSILON4 {
            edges.east.push(EdgeVertex {
                new_index: new_idx,
                uv,
            });
        }
        if (u - threshold_u).abs() < EPSILON4 {
            if keep_above_u {
                edges.west.push(EdgeVertex {
                    new_index: new_idx,
                    uv,
                });
            } else {
                edges.east.push(EdgeVertex {
                    new_index: new_idx,
                    uv,
                });
            }
        }
        if (v - south_v).abs() < EPSILON4 {
            edges.south.push(EdgeVertex {
                new_index: new_idx,
                uv,
            });
        }
        if (v - north_v).abs() < EPSILON4 {
            edges.north.push(EdgeVertex {
                new_index: new_idx,
                uv,
            });
        }
        if (v - threshold_v).abs() < EPSILON4 {
            if keep_above_v {
                edges.south.push(EdgeVertex {
                    new_index: new_idx,
                    uv,
                });
            } else {
                edges.north.push(EdgeVertex {
                    new_index: new_idx,
                    uv,
                });
            }
        }
    }
}

/// Append a skirt strip along a sorted edge.
///
/// Each adjacent pair of edge vertices spawns two triangles (a quad).
fn add_skirt_strip(
    new_floats: &mut Vec<f32>,
    indices: &mut Vec<u32>,
    attrs: &[FloatAttr<'_>],
    edge_vertices: &[u32], // sorted new vertex indices
    mesh_center: DVec3,
    skirt_height: f64,
    vertex_size: usize,
    position_attr_idx: usize, // index into `attrs` for POSITION
    ellipsoid: &terra::Ellipsoid,
) {
    let mut new_edge_start = (new_floats.len() / vertex_size) as u32;

    for (i, &edge_idx) in edge_vertices.iter().enumerate() {
        // Copy all attribute values for this edge vertex.
        let base_float_offset = edge_idx as usize * vertex_size;
        let base_slice =
            &new_floats[base_float_offset * 4 / 4..base_float_offset * 4 / 4 + vertex_size];

        let mut new_vertex: Vec<f32> = base_slice.to_vec();

        // Displace the POSITION component downward along the geodetic normal.
        let pos_offset: usize = attrs[..position_attr_idx]
            .iter()
            .map(|a| a.num_floats)
            .sum();
        let px = new_vertex[pos_offset] as f64 + mesh_center.x;
        let py = new_vertex[pos_offset + 1] as f64 + mesh_center.y;
        let pz = new_vertex[pos_offset + 2] as f64 + mesh_center.z;
        let pos = DVec3::new(px, py, pz);
        let normal = ellipsoid.geodetic_surface_normal(pos);
        let skirt_pos = pos - normal * skirt_height - mesh_center;
        new_vertex[pos_offset] = skirt_pos.x as f32;
        new_vertex[pos_offset + 1] = skirt_pos.y as f32;
        new_vertex[pos_offset + 2] = skirt_pos.z as f32;

        new_floats.extend_from_slice(&new_vertex);

        // Emit two triangles for [i, i+1] quad (if not the last vertex).
        if i + 1 < edge_vertices.len() {
            let next_edge_idx = edge_vertices[i + 1];
            let next_skirt = new_edge_start + 1;
            indices.extend_from_slice(&[
                edge_idx,
                next_edge_idx,
                new_edge_start,
                new_edge_start,
                next_edge_idx,
                next_skirt,
            ]);
        }

        new_edge_start += 1;
    }
}

/// Upsample a single `result.meshes[mesh_i].primitives[prim_i]` *in place*.
///
/// Returns `true` if the primitive should be kept (it has geometry in the
/// child quadrant), `false` if it should be removed.
#[allow(clippy::too_many_arguments)]
fn upsample_primitive(
    parent: &GltfModel,
    result: &mut GltfModel,
    mesh_i: usize,
    prim_i: usize,
    child_id: UpsampleChildId,
    has_inverted_v: bool,
    // All attributes whose name starts with this prefix are stripped from the
    // output - they will be regenerated by the overlay engine.
    texcoord_attr_base: &str,
    // The exact attribute used as the clip guide (a member of the prefix family).
    uv_attr_name: &str,
    ellipsoid: &terra::Ellipsoid,
) -> bool {
    // Collect all info that requires an immutable borrow of `result`
    // We must drop these borrows before any mutable borrow (e.g. build_float_attr).

    let uv_acc_idx = match result.meshes[mesh_i].primitives[prim_i]
        .attributes
        .get(uv_attr_name)
        .copied()
    {
        Some(i) => i,
        None => return false,
    };

    // Snapshot attribute name->index pairs and extras from the result primitive
    // (which is a clone of parent's primitive at this point).
    let attr_pairs: Vec<(String, usize)> = result.meshes[mesh_i].primitives[prim_i]
        .attributes
        .iter()
        .map(|(k, &v)| (k.clone(), v))
        .collect();

    let skirt_meta: Option<SkirtMeshMetadata> = result.meshes[mesh_i].primitives[prim_i]
        .extras
        .as_ref()
        .and_then(SkirtMeshMetadata::parse_from_extras);

    // Resolve UV data from the PARENT model
    let uv_view = match read_vec2_accessor(parent, uv_acc_idx) {
        Some(v) => v,
        None => return false,
    };
    let vertex_count = uv_view.len();

    // Collect non-UV float attributes (mutates result.accessors)
    let mut attrs: Vec<FloatAttr<'_>> = Vec::new();
    let mut attrs_to_remove: Vec<String> = Vec::new();
    // Mapping: orig_acc_idx -> new_acc_idx (for patching primitive.attributes).
    let mut acc_remap: Vec<(usize, usize)> = Vec::new();
    let mut position_attr_idx: Option<usize> = None;

    for (name, orig_acc_idx) in &attr_pairs {
        // Strip every overlay/texcoord attribute - they are regenerated by the
        // overlay engine after upsampling.
        if name.starts_with(texcoord_attr_base) {
            attrs_to_remove.push(name.clone());
            continue;
        }
        match build_float_attr(parent, result, *orig_acc_idx) {
            Some((fa, out_acc)) => {
                if name == "POSITION" {
                    position_attr_idx = Some(attrs.len());
                }
                acc_remap.push((*orig_acc_idx, out_acc));
                attrs.push(FloatAttr {
                    out_acc_idx: out_acc,
                    ..fa
                });
            }
            None => {
                attrs_to_remove.push(name.clone());
            }
        }
    }

    let vertex_size: usize = attrs.iter().map(|a| a.num_floats).sum();
    if vertex_size == 0 {
        return false;
    }

    let raw_indices = read_indices(parent, &parent.meshes[mesh_i].primitives[prim_i]);
    if raw_indices.is_empty() && vertex_count == 0 {
        return false;
    }
    let (indices_begin, indices_count) = if let Some(sm) = &skirt_meta {
        (
            sm.no_skirt_indices_begin as usize,
            sm.no_skirt_indices_count as usize,
        )
    } else {
        (0, raw_indices.len())
    };

    let keep_above_u = !child_id.is_west();
    // Geographic direction: south child keeps V in [0, 0.5] when V=0 is south.
    // This variable is also passed directly to record_edge_vertices so boundary
    // vertices are assigned to the correct edge.
    let keep_above_v = !child_id.is_south();
    // Clip direction: when V is inverted (V=0 at north) we flip the threshold.
    let k_v = if has_inverted_v {
        !keep_above_v
    } else {
        keep_above_v
    };

    let mut new_floats: Vec<f32> = Vec::new();
    let mut new_indices: Vec<u32> = Vec::new();
    let mut vertex_map: Vec<u32> = vec![u32::MAX; vertex_count];
    let mut edge_indices = EdgeIndices::default();

    // UV accessor for clipping guidance only.
    let uv_fa = build_float_attr_raw(parent, uv_acc_idx);

    let mut clipped_a: Vec<CV> = Vec::with_capacity(4);
    let mut clipped_b: Vec<CV> = Vec::with_capacity(4);
    let mut clip_vtx_to_idx: Vec<u32> = Vec::with_capacity(4);

    let idx_end = indices_begin + indices_count;
    let mut i = indices_begin;
    while i + 2 < idx_end + 1 && i + 2 <= idx_end {
        let i0 = raw_indices[i] as i32;
        let i1 = raw_indices[i + 1] as i32;
        let i2 = raw_indices[i + 2] as i32;
        i += 3;

        let uv0 = uv_view[i0 as usize];
        let uv1 = uv_view[i1 as usize];
        let uv2 = uv_view[i2 as usize];

        // Pass 1 - clip along U.
        clipped_a.clear();
        clip_triangle(
            0.5,
            keep_above_u,
            i0,
            i1,
            i2,
            uv0[0] as f64,
            uv1[0] as f64,
            uv2[0] as f64,
            &mut clipped_a,
        );
        if clipped_a.len() < 3 {
            continue;
        }

        // Pass 2 - clip clipped_a[0..3] along V.
        let uv_a0 = eval_uv(&uv_fa, &clipped_a, clipped_a[0]);
        let uv_a1 = eval_uv(&uv_fa, &clipped_a, clipped_a[1]);
        let uv_a2 = eval_uv(&uv_fa, &clipped_a, clipped_a[2]);
        clipped_b.clear();
        clip_triangle(
            0.5,
            k_v,
            !0,
            !1,
            !2,
            uv_a0[1] as f64,
            uv_a1[1] as f64,
            uv_a2[1] as f64,
            &mut clipped_b,
        );
        clip_vtx_to_idx.clear();
        add_clipped_polygon(
            &mut new_floats,
            &mut new_indices,
            &attrs,
            &mut vertex_map,
            &mut clip_vtx_to_idx,
            &clipped_a,
            &clipped_b,
            vertex_size,
        );
        if skirt_meta.is_some() && position_attr_idx.is_some() {
            let uv_fa_slice = std::slice::from_ref(&uv_fa);
            record_edge_vertices(
                &mut edge_indices,
                0.5,
                0.5,
                keep_above_u,
                keep_above_v,
                has_inverted_v,
                &clip_vtx_to_idx,
                uv_fa_slice,
                &clipped_a,
                &clipped_b,
            );
        }

        // If the U-clip produced a quad (4 vertices), process the second triangle.
        if clipped_a.len() > 3 {
            let uv_a3 = eval_uv(&uv_fa, &clipped_a, clipped_a[3]);
            clipped_b.clear();
            clip_triangle(
                0.5,
                k_v,
                !0,
                !2,
                !3,
                uv_a0[1] as f64,
                uv_a2[1] as f64,
                uv_a3[1] as f64,
                &mut clipped_b,
            );
            clip_vtx_to_idx.clear();
            add_clipped_polygon(
                &mut new_floats,
                &mut new_indices,
                &attrs,
                &mut vertex_map,
                &mut clip_vtx_to_idx,
                &clipped_a,
                &clipped_b,
                vertex_size,
            );
            if skirt_meta.is_some() && position_attr_idx.is_some() {
                let uv_fa_slice = std::slice::from_ref(&uv_fa);
                record_edge_vertices(
                    &mut edge_indices,
                    0.5,
                    0.5,
                    keep_above_u,
                    keep_above_v,
                    has_inverted_v,
                    &clip_vtx_to_idx,
                    uv_fa_slice,
                    &clipped_a,
                    &clipped_b,
                );
            }
        }
    }

    if new_floats.is_empty() || new_indices.is_empty() {
        return false;
    }

    let no_skirt_indices_count = new_indices.len() as u32;
    let no_skirt_vertices_count = (new_floats.len() / vertex_size) as u32;

    let new_skirt_meta =
        if let (Some(parent_skirt), Some(pos_idx)) = (skirt_meta, position_attr_idx) {
            let mesh_center = DVec3::from(parent_skirt.mesh_center);
            let shortest = parent_skirt
                .skirt_west_height
                .min(parent_skirt.skirt_east_height)
                .min(parent_skirt.skirt_south_height)
                .min(parent_skirt.skirt_north_height);

            let west_ht = if child_id.is_west() {
                parent_skirt.skirt_west_height
            } else {
                shortest * 0.5
            };
            let east_ht = if !child_id.is_west() {
                parent_skirt.skirt_east_height
            } else {
                shortest * 0.5
            };
            let south_ht = if child_id.is_south() {
                parent_skirt.skirt_south_height
            } else {
                shortest * 0.5
            };
            let north_ht = if !child_id.is_south() {
                parent_skirt.skirt_north_height
            } else {
                shortest * 0.5
            };

            // Sort and emit each edge.
            let mut w: Vec<&EdgeVertex> = edge_indices.west.iter().collect();
            w.sort_by(|a, b| a.uv[1].partial_cmp(&b.uv[1]).unwrap());
            let w_idx: Vec<u32> = w.iter().map(|e| e.new_index).collect();
            add_skirt_strip(
                &mut new_floats,
                &mut new_indices,
                &attrs,
                &w_idx,
                mesh_center,
                west_ht,
                vertex_size,
                pos_idx,
                ellipsoid,
            );

            let mut s: Vec<&EdgeVertex> = edge_indices.south.iter().collect();
            s.sort_by(|a, b| b.uv[0].partial_cmp(&a.uv[0]).unwrap()); // east->west
            let s_idx: Vec<u32> = if has_inverted_v {
                s.iter().rev().map(|e| e.new_index).collect()
            } else {
                s.iter().map(|e| e.new_index).collect()
            };
            add_skirt_strip(
                &mut new_floats,
                &mut new_indices,
                &attrs,
                &s_idx,
                mesh_center,
                south_ht,
                vertex_size,
                pos_idx,
                ellipsoid,
            );

            let mut e: Vec<&EdgeVertex> = edge_indices.east.iter().collect();
            e.sort_by(|a, b| b.uv[1].partial_cmp(&a.uv[1]).unwrap()); // north->south
            let e_idx: Vec<u32> = e.iter().map(|e| e.new_index).collect();
            add_skirt_strip(
                &mut new_floats,
                &mut new_indices,
                &attrs,
                &e_idx,
                mesh_center,
                east_ht,
                vertex_size,
                pos_idx,
                ellipsoid,
            );

            let mut n: Vec<&EdgeVertex> = edge_indices.north.iter().collect();
            n.sort_by(|a, b| a.uv[0].partial_cmp(&b.uv[0]).unwrap()); // west->east
            let n_idx: Vec<u32> = if has_inverted_v {
                n.iter().rev().map(|e| e.new_index).collect()
            } else {
                n.iter().map(|e| e.new_index).collect()
            };
            add_skirt_strip(
                &mut new_floats,
                &mut new_indices,
                &attrs,
                &n_idx,
                mesh_center,
                north_ht,
                vertex_size,
                pos_idx,
                ellipsoid,
            );

            Some(SkirtMeshMetadata {
                no_skirt_indices_begin: 0,
                no_skirt_indices_count,
                no_skirt_vertices_begin: 0,
                no_skirt_vertices_count,
                mesh_center: parent_skirt.mesh_center,
                skirt_west_height: west_ht,
                skirt_south_height: south_ht,
                skirt_east_height: east_ht,
                skirt_north_height: north_ht,
            })
        } else {
            None
        };

    // Layout: [attr0_c0..attr0_cn | attr1_c0..attr1_cn | ...] per vertex.
    let num_vertices = new_floats.len() / vertex_size;
    let mut attr_mins: Vec<Vec<f64>> = attrs.iter().map(|a| vec![f64::MAX; a.num_floats]).collect();
    let mut attr_maxs: Vec<Vec<f64>> = attrs.iter().map(|a| vec![f64::MIN; a.num_floats]).collect();
    for v in 0..num_vertices {
        let mut component_offset = v * vertex_size;
        for (ai, attr) in attrs.iter().enumerate() {
            for c in 0..attr.num_floats {
                let val = new_floats[component_offset + c] as f64;
                if val < attr_mins[ai][c] {
                    attr_mins[ai][c] = val;
                }
                if val > attr_maxs[ai][c] {
                    attr_maxs[ai][c] = val;
                }
            }
            component_offset += attr.num_floats;
        }
    }

    let vertex_bytes: &[u8] = bytemuck::cast_slice(&new_floats);
    let index_bytes: &[u8] = bytemuck::cast_slice(&new_indices);

    // Vertex buffer.
    let vbuf_idx = result.buffers.len();
    result.buffers.push(Buffer {
        byte_length: vertex_bytes.len(),
        data: vertex_bytes.to_vec(),
        ..Default::default()
    });
    let vbv_idx = result.buffer_views.len();
    result.buffer_views.push(BufferView {
        buffer: vbuf_idx,
        byte_offset: 0,
        byte_length: vertex_bytes.len(),
        byte_stride: Some(vertex_size * 4),
        ..Default::default()
    });

    // Index buffer.
    let ibuf_idx = result.buffers.len();
    result.buffers.push(Buffer {
        byte_length: index_bytes.len(),
        data: index_bytes.to_vec(),
        ..Default::default()
    });
    let ibv_idx = result.buffer_views.len();
    result.buffer_views.push(BufferView {
        buffer: ibuf_idx,
        byte_offset: 0,
        byte_length: index_bytes.len(),
        ..Default::default()
    });

    // Update accessor byte offsets, counts, and min/max.
    let mut float_offset = 0usize;
    for (ai, attr) in attrs.iter().enumerate() {
        let acc = &mut result.accessors[attr.out_acc_idx];
        acc.buffer_view = Some(vbv_idx);
        acc.byte_offset = float_offset * 4;
        acc.count = num_vertices;
        acc.min = attr_mins[ai].clone();
        acc.max = attr_maxs[ai].clone();
        float_offset += attr.num_floats;
    }

    // Index accessor.
    let idx_acc_idx = result.accessors.len();
    result.accessors.push(Accessor {
        buffer_view: Some(ibv_idx),
        byte_offset: 0,
        component_type: AccessorComponentType::UnsignedInt,
        count: new_indices.len(),
        r#type: AccessorType::Scalar,
        ..Default::default()
    });

    // Patch the primitive: update attribute accessor indices and index accessor.
    let prim = &mut result.meshes[mesh_i].primitives[prim_i];

    // Remove the UV clipping attribute and any skipped non-float attributes.
    prim.attributes
        .retain(|name, _| !attrs_to_remove.contains(name));

    // Remap each kept attribute to its new output accessor.
    for (orig_idx, new_idx) in &acc_remap {
        for v in prim.attributes.values_mut() {
            if *v == *orig_idx {
                *v = *new_idx;
            }
        }
    }
    prim.indices = Some(idx_acc_idx);

    // Write back skirt metadata.
    if let Some(sm) = new_skirt_meta {
        prim.extras = Some(sm.to_extras_value());
    } else {
        prim.extras = None;
    }

    true
}

/// Build a [`FloatAttr`] pointing into the PARENT model's raw bytes, and
/// pre-create the corresponding accessor in the OUTPUT model.
///
/// Returns `None` for non-FLOAT accessors or if accessor resolution fails.
fn build_float_attr<'parent>(
    parent: &'parent GltfModel,
    result: &mut GltfModel,
    acc_idx: usize,
) -> Option<(FloatAttr<'parent>, usize)> {
    let acc = parent.accessors.get(acc_idx)?;
    if acc.component_type != AccessorComponentType::Float {
        return None;
    }
    let bv_idx = acc.buffer_view?;
    let bv = parent.buffer_views.get(bv_idx)?;
    let buf = parent.buffers.get(bv.buffer)?;
    let num_floats = acc.r#type.num_components() as usize;
    let stride = bv.byte_stride.unwrap_or(num_floats * 4);
    let byte_offset = bv.byte_offset + acc.byte_offset;

    // Pre-create the output accessor (buffer_view / byte_offset will be
    // updated after the interleaved buffer is written).
    let out_acc_idx = result.accessors.len();
    result.accessors.push(Accessor {
        buffer_view: None,
        byte_offset: 0,
        component_type: AccessorComponentType::Float,
        count: 0,
        r#type: acc.r#type,
        ..Default::default()
    });

    Some((
        FloatAttr {
            data: &buf.data,
            byte_offset,
            stride,
            num_floats,
            out_acc_idx,
        },
        out_acc_idx,
    ))
}

/// Build a bare `FloatAttr` from the parent model without creating an output
/// accessor.  Used for reading UV data used only for clipping.
fn build_float_attr_raw(parent: &GltfModel, acc_idx: usize) -> FloatAttr<'_> {
    let acc = &parent.accessors[acc_idx];
    let bv_idx = acc.buffer_view.unwrap_or(0);
    let bv = &parent.buffer_views[bv_idx];
    let buf = &parent.buffers[bv.buffer];
    let num_floats = acc.r#type.num_components() as usize;
    let stride = bv.byte_stride.unwrap_or(num_floats * 4);
    FloatAttr {
        data: &buf.data,
        byte_offset: bv.byte_offset + acc.byte_offset,
        stride,
        num_floats,
        out_acc_idx: 0,
    }
}

/// Read a vec2 UV accessor from the parent model into a plain `Vec<[f32;2]>`.
fn read_vec2_accessor(parent: &GltfModel, acc_idx: usize) -> Option<Vec<[f32; 2]>> {
    let acc = parent.accessors.get(acc_idx)?;
    let bv_idx = acc.buffer_view?;
    let bv = parent.buffer_views.get(bv_idx)?;
    let buf = parent.buffers.get(bv.buffer)?;
    let stride = bv.byte_stride.unwrap_or(8);
    let base = bv.byte_offset + acc.byte_offset;
    let data = &buf.data;
    let mut out = Vec::with_capacity(acc.count);
    for i in 0..acc.count {
        let s = base + i * stride;
        let u = f32::from_le_bytes(data[s..s + 4].try_into().ok()?);
        let v = f32::from_le_bytes(data[s + 4..s + 8].try_into().ok()?);
        out.push([u, v]);
    }
    Some(out)
}

/// Read the index buffer of a primitive, returning all indices as `u32`.
/// Returns an empty vec for non-indexed (unindexed) primitives - the caller
/// handles them as sequential vertex triples.
fn read_indices(parent: &GltfModel, prim: &MeshPrimitive) -> Vec<u32> {
    let acc_idx = match prim.indices {
        Some(i) => i,
        None => return vec![],
    };
    let acc = match parent.accessors.get(acc_idx) {
        Some(a) => a,
        None => return vec![],
    };
    let bv_idx = match acc.buffer_view {
        Some(i) => i,
        None => return vec![],
    };
    let bv = &parent.buffer_views[bv_idx];
    let buf = &parent.buffers[bv.buffer];
    let data = &buf.data;
    let base = bv.byte_offset + acc.byte_offset;

    match acc.component_type {
        AccessorComponentType::UnsignedByte => {
            (0..acc.count).map(|i| data[base + i] as u32).collect()
        }
        AccessorComponentType::UnsignedShort => (0..acc.count)
            .map(|i| {
                let s = base + i * 2;
                u16::from_le_bytes(data[s..s + 2].try_into().unwrap()) as u32
            })
            .collect(),
        _ => (0..acc.count)
            .map(|i| {
                let s = base + i * 4;
                u32::from_le_bytes(data[s..s + 4].try_into().unwrap())
            })
            .collect(),
    }
}

/// Evaluate a `CV` entry to a `[f32; 2]` UV using a bare `FloatAttr`.
fn eval_uv(uv_fa: &FloatAttr<'_>, complements: &[CV], v: CV) -> [f32; 2] {
    let floats = eval_cv(std::slice::from_ref(uv_fa), complements, v);
    [floats[0], floats[1]]
}

/// Add a clipped polygon (3 or 4 vertices from `clip_b`) as triangles to
/// `new_floats` / `new_indices`, updating `vertex_map` and appending to
/// `clip_vtx_to_idx`.
fn add_clipped_polygon(
    new_floats: &mut Vec<f32>,
    new_indices: &mut Vec<u32>,
    attrs: &[FloatAttr<'_>],
    vertex_map: &mut [u32],
    clip_vtx_to_idx: &mut Vec<u32>,
    complements: &[CV],
    clip_b: &[CV],
    vertex_size: usize,
) {
    if clip_b.len() < 3 {
        return;
    }

    let i0 = get_or_create(
        new_floats,
        attrs,
        complements,
        clip_b[0],
        vertex_size,
        vertex_map,
    );
    let i1 = get_or_create(
        new_floats,
        attrs,
        complements,
        clip_b[1],
        vertex_size,
        vertex_map,
    );
    let i2 = get_or_create(
        new_floats,
        attrs,
        complements,
        clip_b[2],
        vertex_size,
        vertex_map,
    );

    new_indices.extend_from_slice(&[i0, i1, i2]);
    clip_vtx_to_idx.extend_from_slice(&[i0, i1, i2]);

    if clip_b.len() > 3 {
        let i3 = get_or_create(
            new_floats,
            attrs,
            complements,
            clip_b[3],
            vertex_size,
            vertex_map,
        );
        new_indices.extend_from_slice(&[i0, i2, i3]);
        clip_vtx_to_idx.push(i3);
    }
}
