// This file was generated by schema-gen.
// DO NOT EDIT THIS FILE!

//! Generated types.

#![allow(clippy::all)]

use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::collections::HashMap;

/// Data type of accessor components (5120: BYTE, 5121: UNSIGNED_BYTE, 5122: SHORT, 5123: UNSIGNED_SHORT, 5125: UNSIGNED_INT, 5126: FLOAT).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AccessorComponentType {
    Byte,
    UnsignedByte,
    Short,
    UnsignedShort,
    UnsignedInt,
    Float,
}

impl Serialize for AccessorComponentType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let value: u32 = match self {
            Self::Byte => 5120,
            Self::UnsignedByte => 5121,
            Self::Short => 5122,
            Self::UnsignedShort => 5123,
            Self::UnsignedInt => 5125,
            Self::Float => 5126,
        };
        serializer.serialize_u32(value)
    }
}

impl<'de> Deserialize<'de> for AccessorComponentType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = u32::deserialize(deserializer)?;
        match value {
            5120 => Ok(Self::Byte),
            5121 => Ok(Self::UnsignedByte),
            5122 => Ok(Self::Short),
            5123 => Ok(Self::UnsignedShort),
            5125 => Ok(Self::UnsignedInt),
            5126 => Ok(Self::Float),
            _ => Err(serde::de::Error::custom(format!(
                "invalid AccessorComponentType value: {}",
                value
            ))),
        }
    }
}

impl Default for AccessorComponentType {
    fn default() -> Self {
        Self::Byte
    }
}

/// Camera projection type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CameraType {
    #[serde(rename = "perspective")]
    Perspective,
    #[serde(rename = "orthographic")]
    Orthographic,
}

impl Default for CameraType {
    fn default() -> Self {
        Self::Perspective
    }
}

/// Primitive rendering mode (0: POINTS, 1: LINES, 2: LINE_LOOP, 3: LINE_STRIP, 4: TRIANGLES, 5: TRIANGLE_STRIP, 6: TRIANGLE_FAN).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PrimitiveMode {
    Points,
    Lines,
    LineLoop,
    LineStrip,
    Triangles,
    TriangleStrip,
    TriangleFan,
}

impl Serialize for PrimitiveMode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let value: u32 = match self {
            Self::Points => 0,
            Self::Lines => 1,
            Self::LineLoop => 2,
            Self::LineStrip => 3,
            Self::Triangles => 4,
            Self::TriangleStrip => 5,
            Self::TriangleFan => 6,
        };
        serializer.serialize_u32(value)
    }
}

impl<'de> Deserialize<'de> for PrimitiveMode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = u32::deserialize(deserializer)?;
        match value {
            0 => Ok(Self::Points),
            1 => Ok(Self::Lines),
            2 => Ok(Self::LineLoop),
            3 => Ok(Self::LineStrip),
            4 => Ok(Self::Triangles),
            5 => Ok(Self::TriangleStrip),
            6 => Ok(Self::TriangleFan),
            _ => Err(serde::de::Error::custom(format!(
                "invalid PrimitiveMode value: {}",
                value
            ))),
        }
    }
}

impl Default for PrimitiveMode {
    fn default() -> Self {
        Self::Points
    }
}

/// Accessor type: specifies whether data is scalars, vectors, or matrices.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AccessorType {
    #[serde(rename = "SCALAR")]
    Scalar,
    #[serde(rename = "VEC2")]
    Vec2,
    #[serde(rename = "VEC3")]
    Vec3,
    #[serde(rename = "VEC4")]
    Vec4,
    #[serde(rename = "MAT2")]
    Mat2,
    #[serde(rename = "MAT3")]
    Mat3,
    #[serde(rename = "MAT4")]
    Mat4,
}

impl Default for AccessorType {
    fn default() -> Self {
        Self::Scalar
    }
}

/// Animated property name (translation, rotation, scale, or weights).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AnimationPath {
    #[serde(rename = "translation")]
    Translation,
    #[serde(rename = "rotation")]
    Rotation,
    #[serde(rename = "scale")]
    Scale,
    #[serde(rename = "weights")]
    Weights,
}

impl Default for AnimationPath {
    fn default() -> Self {
        Self::Translation
    }
}

/// Interpolation algorithm for animation samplers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AnimationInterpolation {
    #[serde(rename = "LINEAR")]
    Linear,
    #[serde(rename = "STEP")]
    Step,
    #[serde(rename = "CUBICSPLINE")]
    Cubicspline,
}

impl Default for AnimationInterpolation {
    fn default() -> Self {
        Self::Linear
    }
}

/// Alpha blending mode for materials.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlphaMode {
    #[serde(rename = "OPAQUE")]
    Opaque,
    #[serde(rename = "MASK")]
    Mask,
    #[serde(rename = "BLEND")]
    Blend,
}

impl Default for AlphaMode {
    fn default() -> Self {
        Self::Opaque
    }
}

/// A typed view into a buffer view that contains raw binary data.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Accessor {
    /// The index of the bufferView.
    #[serde(
        rename = "bufferView",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub buffer_view: Option<usize>,

    /// The offset relative to the start of the buffer view in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: usize,

    /// The datatype of the accessor's components.
    #[serde(rename = "componentType")]
    pub component_type: AccessorComponentType,

    /// The number of elements referenced by this accessor.
    pub count: usize,

    /// Maximum value of each component in this accessor.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub max: Vec<f64>,

    /// Minimum value of each component in this accessor.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub min: Vec<f64>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// Specifies whether integer data values are normalized before usage.
    #[serde(default)]
    pub normalized: bool,

    /// Sparse storage of elements that deviate from their initialization value.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sparse: Option<AccessorSparse>,

    /// Specifies if the accessor's elements are scalars, vectors, or matrices.
    #[serde(rename = "type")]
    pub r#type: AccessorType,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Sparse storage of accessor values that deviate from their initialization value.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessorSparse {
    /// Number of deviating accessor values stored in the sparse array.
    pub count: u64,

    /// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `count`. Indices **MUST** strictly increase.
    pub indices: AccessorSparseIndices,

    /// An object pointing to a buffer view containing the deviating accessor values.
    pub values: AccessorSparseValues,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `accessor.sparse.count`. Indices **MUST** strictly increase.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessorSparseIndices {
    /// The index of the buffer view with sparse indices. The referenced buffer view **MUST NOT** have its `target` or `byteStride` properties defined. The buffer view and the optional `byteOffset` **MUST** be aligned to the `componentType` byte length.
    #[serde(rename = "bufferView")]
    pub buffer_view: usize,

    /// The offset relative to the start of the buffer view in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: usize,

    /// The indices data type.
    #[serde(rename = "componentType")]
    pub component_type: AccessorComponentType,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object pointing to a buffer view containing the deviating accessor values. The number of elements is equal to `accessor.sparse.count` times number of components. The elements have the same component type as the base accessor. The elements are tightly packed. Data **MUST** be aligned following the same rules as the base accessor.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessorSparseValues {
    /// The index of the bufferView with sparse values. The referenced buffer view **MUST NOT** have its `target` or `byteStride` properties defined.
    #[serde(rename = "bufferView")]
    pub buffer_view: usize,

    /// The offset relative to the start of the bufferView in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: usize,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A keyframe animation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Animation {
    /// An array of animation channels. An animation channel combines an animation sampler with a target property being animated. Different channels of the same animation **MUST NOT** have the same targets.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub channels: Vec<AnimationChannel>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// An array of animation samplers. An animation sampler combines timestamps with a sequence of output values and defines an interpolation algorithm.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub samplers: Vec<AnimationSampler>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An animation channel combines an animation sampler with a target property being animated.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnimationChannel {
    /// The index of a sampler in this animation used to compute the value for the target.
    pub sampler: usize,

    /// The descriptor of the animated property.
    pub target: AnimationChannelTarget,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The descriptor of the animated property.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnimationChannelTarget {
    /// The index of the node to animate. When undefined, the animated object **MAY** be defined by an extension.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub node: Option<usize>,

    /// The name of the node's TRS property to animate, or the `"weights"` of the Morph Targets it instantiates. For the `"translation"` property, the values that are provided by the sampler are the translation along the X, Y, and Z axes. For the `"rotation"` property, the values are a quaternion in the order (x, y, z, w), where w is the scalar. For the `"scale"` property, the values are the scaling factors along the X, Y, and Z axes.
    pub path: AnimationPath,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An animation sampler combines timestamps with a sequence of output values and defines an interpolation algorithm.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnimationSampler {
    /// The index of an accessor containing keyframe timestamps.
    pub input: usize,

    /// Interpolation algorithm.
    #[serde(default)]
    pub interpolation: AnimationInterpolation,

    /// The index of an accessor, containing keyframe output values.
    pub output: usize,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Metadata about the glTF asset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// A copyright message suitable for display to credit the content creator.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub copyright: Option<String>,

    /// Tool that generated this glTF model.  Useful for debugging.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub generator: Option<String>,

    /// The minimum glTF version in the form of `<major>.<minor>` that this asset targets. This property **MUST NOT** be greater than the asset version.
    #[serde(
        rename = "minVersion",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub min_version: Option<String>,

    /// The glTF version in the form of `<major>.<minor>` that this asset targets.
    pub version: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A buffer points to binary geometry, animation, or skins.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Buffer {
    /// The length of the buffer in bytes.
    #[serde(rename = "byteLength")]
    pub byte_length: usize,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The URI (or IRI) of the buffer.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub uri: Option<String>,

    /// Runtime binary payload. Not part of the glTF JSON schema; skipped during (de)serialization.
    #[serde(skip)]
    pub data: Vec<u8>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A view into a buffer generally representing a subset of the buffer.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BufferView {
    /// The index of the buffer.
    pub buffer: usize,

    /// The length of the bufferView in bytes.
    #[serde(rename = "byteLength")]
    pub byte_length: usize,

    /// The offset into the buffer in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: usize,

    /// The stride, in bytes.
    #[serde(
        rename = "byteStride",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub byte_stride: Option<usize>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The hint representing the intended GPU buffer type to use with this buffer view.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub target: Option<u32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A camera's projection.  A node **MAY** reference a camera to apply a transform to place the camera in the scene.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Camera {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// An orthographic camera containing properties to create an orthographic projection matrix. This property **MUST NOT** be defined when `perspective` is defined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub orthographic: Option<CameraOrthographic>,

    /// A perspective camera containing properties to create a perspective projection matrix. This property **MUST NOT** be defined when `orthographic` is defined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub perspective: Option<CameraPerspective>,

    /// Specifies if the camera uses a perspective or orthographic projection.
    #[serde(rename = "type")]
    pub r#type: CameraType,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An orthographic camera containing properties to create an orthographic projection matrix.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CameraOrthographic {
    /// The floating-point horizontal magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
    pub xmag: f64,

    /// The floating-point vertical magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
    pub ymag: f64,

    /// The floating-point distance to the far clipping plane. This value **MUST NOT** be equal to zero. `zfar` **MUST** be greater than `znear`.
    pub zfar: f64,

    /// The floating-point distance to the near clipping plane.
    pub znear: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A perspective camera containing properties to create a perspective projection matrix.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CameraPerspective {
    /// The floating-point aspect ratio of the field of view.
    #[serde(
        rename = "aspectRatio",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub aspect_ratio: Option<f64>,

    /// The floating-point vertical field of view in radians. This value **SHOULD** be less than \pi.
    pub yfov: f64,

    /// The floating-point distance to the far clipping plane.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub zfar: Option<f64>,

    /// The floating-point distance to the near clipping plane.
    pub znear: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The root object for a glTF asset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GltfModel {
    /// An array of accessors.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub accessors: Vec<Accessor>,

    /// An array of keyframe animations.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub animations: Vec<Animation>,

    /// Metadata about the glTF asset.
    pub asset: Asset,

    /// An array of bufferViews.
    #[serde(rename = "bufferViews", skip_serializing_if = "Vec::is_empty", default)]
    pub buffer_views: Vec<BufferView>,

    /// An array of buffers.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub buffers: Vec<Buffer>,

    /// An array of cameras.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub cameras: Vec<Camera>,

    /// Names of glTF extensions required to properly load this asset.
    #[serde(
        rename = "extensionsRequired",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub extensions_required: Vec<String>,

    /// Names of glTF extensions used in this asset.
    #[serde(
        rename = "extensionsUsed",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub extensions_used: Vec<String>,

    /// An array of images.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub images: Vec<Image>,

    /// An array of materials.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub materials: Vec<Material>,

    /// An array of meshes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub meshes: Vec<Mesh>,

    /// An array of nodes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub nodes: Vec<Node>,

    /// An array of samplers.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub samplers: Vec<Sampler>,

    /// The index of the default scene.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub scene: Option<usize>,

    /// An array of scenes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub scenes: Vec<Scene>,

    /// An array of skins.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub skins: Vec<Skin>,

    /// An array of textures.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub textures: Vec<Texture>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Image data used to create a texture. Image **MAY** be referenced by an URI (or IRI) or a buffer view index.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Image {
    /// The index of the bufferView that contains the image. This field **MUST NOT** be defined when `uri` is defined.
    #[serde(
        rename = "bufferView",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub buffer_view: Option<usize>,

    /// The image's media type. This field **MUST** be defined when `bufferView` is defined.
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none", default)]
    pub mime_type: Option<String>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The URI (or IRI) of the image.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub uri: Option<String>,

    /// Decoded pixel data. Populated by the reader pipeline; not serialized.
    #[serde(skip)]
    pub pixels: crate::image::ImageData,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The material appearance of a primitive.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Material {
    /// The alpha cutoff value of the material.
    #[serde(rename = "alphaCutoff", default = "default_material_alpha_cutoff")]
    pub alpha_cutoff: f64,

    /// The alpha rendering mode of the material.
    #[serde(rename = "alphaMode", default)]
    pub alpha_mode: AlphaMode,

    /// Specifies whether the material is double sided.
    #[serde(rename = "doubleSided", default)]
    pub double_sided: bool,

    /// The factors for the emissive color of the material.
    #[serde(
        rename = "emissiveFactor",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub emissive_factor: Vec<f64>,

    /// The emissive texture.
    #[serde(
        rename = "emissiveTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub emissive_texture: Option<TextureInfo>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The tangent space normal texture.
    #[serde(
        rename = "normalTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub normal_texture: Option<MaterialNormalTextureInfo>,

    /// The occlusion texture.
    #[serde(
        rename = "occlusionTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub occlusion_texture: Option<MaterialOcclusionTextureInfo>,

    /// A set of parameter values that are used to define the metallic-roughness material model from Physically Based Rendering (PBR) methodology. When undefined, all the default values of `pbrMetallicRoughness` **MUST** apply.
    #[serde(
        rename = "pbrMetallicRoughness",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub pbr_metallic_roughness: Option<MaterialPbrMetallicRoughness>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_alpha_cutoff() -> f64 {
    0.5
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MaterialNormalTextureInfo {
    /// The index of the texture.
    pub index: usize,

    /// The scalar parameter applied to each normal vector of the normal texture.
    #[serde(default = "default_material_normal_texture_info_scale")]
    pub scale: f64,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: usize,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_normal_texture_info_scale() -> f64 {
    1.0
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MaterialOcclusionTextureInfo {
    /// The index of the texture.
    pub index: usize,

    /// A scalar multiplier controlling the amount of occlusion applied.
    #[serde(default = "default_material_occlusion_texture_info_strength")]
    pub strength: f64,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: usize,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_occlusion_texture_info_strength() -> f64 {
    1.0
}

/// A set of parameter values that are used to define the metallic-roughness material model from Physically-Based Rendering (PBR) methodology.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MaterialPbrMetallicRoughness {
    /// The factors for the base color of the material.
    #[serde(
        rename = "baseColorFactor",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub base_color_factor: Vec<f64>,

    /// The base color texture.
    #[serde(
        rename = "baseColorTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub base_color_texture: Option<TextureInfo>,

    /// The factor for the metalness of the material.
    #[serde(
        rename = "metallicFactor",
        default = "default_material_pbr_metallic_roughness_metallic_factor"
    )]
    pub metallic_factor: f64,

    /// The metallic-roughness texture.
    #[serde(
        rename = "metallicRoughnessTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub metallic_roughness_texture: Option<TextureInfo>,

    /// The factor for the roughness of the material.
    #[serde(
        rename = "roughnessFactor",
        default = "default_material_pbr_metallic_roughness_roughness_factor"
    )]
    pub roughness_factor: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_pbr_metallic_roughness_metallic_factor() -> f64 {
    1.0
}

fn default_material_pbr_metallic_roughness_roughness_factor() -> f64 {
    1.0
}

/// A set of primitives to be rendered.  Its global transform is defined by a node that references it.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Mesh {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// An array of primitives, each defining geometry to be rendered.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub primitives: Vec<MeshPrimitive>,

    /// Array of weights to be applied to the morph targets. The number of array elements **MUST** match the number of morph targets.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub weights: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Geometry to be rendered with the given material.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MeshPrimitive {
    /// A plain JSON object, where each key corresponds to a mesh attribute semantic and each value is the index of the accessor containing attribute's data.
    pub attributes: HashMap<String, usize>,

    /// The index of the accessor that contains the vertex indices.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub indices: Option<usize>,

    /// The index of the material to apply to this primitive when rendering.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub material: Option<usize>,

    /// The topology type of primitives to render.
    #[serde(default)]
    pub mode: PrimitiveMode,

    /// An array of morph targets.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub targets: Option<Vec<HashMap<String, usize>>>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A node in the node hierarchy.  When the node contains `skin`, all `mesh.primitives` **MUST** contain `JOINTS_0` and `WEIGHTS_0` attributes.  A node **MAY** have either a `matrix` or any combination of `translation`/`rotation`/`scale` (TRS) properties. TRS properties are converted to matrices and postmultiplied in the `T * R * S` order to compose the transformation matrix; first the scale is applied to the vertices, then the rotation, and then the translation. If none are provided, the transform is the identity. When a node is targeted for animation (referenced by an animation.channel.target), `matrix` **MUST NOT** be present.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Node {
    /// The index of the camera referenced by this node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub camera: Option<usize>,

    /// The indices of this node's children.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub children: Option<Vec<usize>>,

    /// A floating-point 4x4 transformation matrix stored in column-major order.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub matrix: Vec<f64>,

    /// The index of the mesh in this node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub mesh: Option<usize>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The node's unit quaternion rotation in the order (x, y, z, w), where w is the scalar.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub rotation: Vec<f64>,

    /// The node's non-uniform scale, given as the scaling factors along the x, y, and z axes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub scale: Vec<f64>,

    /// The index of the skin referenced by this node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub skin: Option<usize>,

    /// The node's translation along the x, y, and z axes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub translation: Vec<f64>,

    /// The weights of the instantiated morph target. The number of array elements **MUST** match the number of morph targets of the referenced mesh. When defined, `mesh` **MUST** also be defined.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub weights: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Texture sampler properties for filtering and wrapping modes.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Sampler {
    /// Magnification filter.
    #[serde(rename = "magFilter", skip_serializing_if = "Option::is_none", default)]
    pub mag_filter: Option<u32>,

    /// Minification filter.
    #[serde(rename = "minFilter", skip_serializing_if = "Option::is_none", default)]
    pub min_filter: Option<u32>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// S (U) wrapping mode.
    #[serde(rename = "wrapS", default)]
    pub wrap_s: u32,

    /// T (V) wrapping mode.
    #[serde(rename = "wrapT", default)]
    pub wrap_t: u32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The root nodes of a scene.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Scene {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The indices of each root node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub nodes: Option<Vec<usize>>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Joints and matrices defining a skin.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Skin {
    /// The index of the accessor containing the floating-point 4x4 inverse-bind matrices.
    #[serde(
        rename = "inverseBindMatrices",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub inverse_bind_matrices: Option<usize>,

    /// Indices of skeleton nodes, used as joints in this skin.
    pub joints: Vec<usize>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The index of the node used as a skeleton root.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub skeleton: Option<usize>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A texture and its sampler.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Texture {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering **SHOULD** be used.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sampler: Option<usize>,

    /// The index of the image used by this texture. When undefined, an extension or other mechanism **SHOULD** supply an alternate texture source, otherwise behavior is undefined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub source: Option<usize>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Reference to a texture.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TextureInfo {
    /// The index of the texture.
    pub index: usize,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: usize,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}
